### PR TITLE
Fix path and URI issues on Windows

### PR DESCRIPTION
**Pull request by longwa**
Fixes the "unterminated string literal" issue on Windows (and possibly Mac). Also tested on Linux with no breakage. I have NOT tested on a Mac.

### CODE REVIEW

**Comment by rolaveric** [comment]
Works perfectly for me using this fork.  Thanks!

**Comment by wavyx** [comment]
Please merge this :D

**Comment by sarbogast** [comment]
+1

**Comment by VadimKirilchuk** [comment]
+1 and Thx to longwa.
P.s It would be better to rely on java File api instead of working with path strings directly! Why the plugin works with plain strings!?

**Comment by longwa** [comment]
IIRC, the LESS compiler is being executed externally by the plugin so the paths must be translated prior to making the call to the compiler.

**Pull request merged**
